language: python
python:
  - "2.7"
git:
  depth: 5
# command to install dependencies
install: "pip install -q"
# command to run tests, e.g. python setup.py test
script: nosetests
branches:
  only:
    - master
    - stable
notifications:
  email:
    recipients:
      - ajain@lbl.gov
    on_success: change
    on_failure: always