version: 2

jobs:
  py3test:
    working_directory: ~/fireworks
    docker:
      - image: circleci/python:3.7.3
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
            conda create -q -n test-environment python=3.7
            source activate test-environment
            conda update --quiet --all
            pip install --quiet --ignore-installed -r requirements.txt -r requirements-ci.txt
      - run:
          name: Run fireworks tests
          command: |
            pip install --quiet -e .
            pytest fireworks

workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
